version: '3'
services:
   springboot:
      image: 800161990735.dkr.ecr.ap-south-1.amazonaws.com/spring-boot:VERSION
      ports:
       - 8080:8080
      environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@123
      networks:
       - springbootoverlay
      depends_on:
       - mongo
      deploy:
       replicas: 2
        

   mongo:
      image: mongo
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
      networks:
       - springbootoverlay
      volumes:
       - mongodb:/data/db
networks:
  springbootoverlay:
    external: true
volumes:
  mongodb:
    external: true


