version: '3'
services:
    springbootapp:
      images: lokeshsdockerhub/springboot_mongo:1
      ports:
       - 8080:8080
      environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_USERNAME=devdb@123
      networks:
        - springbootoverlay
      depends_on:
        - mongo
    mongo:
      image: mongo
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
      networks:
        - springbootoverlay
      volumes:
        - mongodbvol:/data/db
networks:
  springbootoverlay:
    driver: overlay
volumes:
  mongodbvol:
    external: true




