version: '3'
services:
   springboot:
      image: lokeshsdockerhub/spring_boot:VERSION
      ports:
       - 9000:9000
      environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@123
      networks:
       - springbootoverlay
      depends_on:
       - mongo
      deploy:
       replicas: 2
        

   mongo:
      image: mongo
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
      networks:
       - springbootoverlay
      volumes:
       - mongodb:/data/db
networks:
  springbootoverlay:
    driver: overlay
volumes:
  mongodb:
    driver: local


