version: '3'
services:
  springbootapp:
    image: lokeshsdockerhub/spring_boot:VERSION
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@123
    networks:
      - springbootappoverlay
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    networks:
      - springbootappoverlay
    volumes:
      - mongodbvol:/data/db
networks:
  springbootappoverlay:
    driver: overlay
volumes:
  mongodbvol:
    external: true
