version: '3'
services:
  springbootapp:
    depends_on:
      - mongo
    image: lokeshsdockerhub/springboot:VERSION
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@123
    networks:
      - springbootappoverlay

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
      - mongodbvol:/data/db
    restart: always
    networks:
    - springbootappoverlay
networks:
  springbootappoverlay:
    driver: overlay
volumes:
  mongodbvol:
    external: true