apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapprs
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      app: springapp
    spec:
     containers:
     - name: springapp
       image: lokeshsdockerhub/springapp:TAG
       ports:
         - containerPort: 8080
       resources:
         requests:
           cpu: 250m
           memory: 512Mi
         limits:
           cpu: 450m
           memory: 800Mi
       env:
       - name: MONGO_DB_HOSTNAME
         value: mongosvc
       - name: MONGO_DB_USERNAME
         value: devdb
       - name: MONGO_DB_PASSWORD
         value: devvdb@123
---
apiVersion: v1 
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000
  
  
